version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.14
    commands:
      - echo Installing frontend dependencies...
      - npm install --prefix frontend
  build:
    commands:
      - echo Building React frontend...
      - npm run build --prefix frontend
      - echo Copying build output...
      - cp -r frontend/build ./static
      - echo Installing Python dependencies...
      - pip install -r requirements.txt

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - frontend/node_modules/**
