version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.14
    commands:
      - pip install -r requirements.txt
      - npm install --prefix frontend
  build:
    commands:
      - npm run build --prefix frontend
      - cp -r frontend/build ./static

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - frontend/node_modules/**
